### ISSUE TITLE
Windows 安装后启动报告语法错误

### ISSUE THREAD

**Issue by chnt7305** [kasuganosoras/Pigeon#1]
syntax error, unexpected end of file in Pigeon\pigeon\loader.php on line 436

**Comment by kasuganosoras** [comment]
也许是你没有开启 PHP 的短标签支持，检查一下 `php.ini` 中的 `short_open_tag` 是否为 true

**Comment by chnt7305** [comment]
@kasuganosoras 确实是没有开启，已经好了，谢谢！
