### ISSUE TITLE
建议：增加更多用户字段

### ISSUE THREAD

**Issue by xzyone** [kasuganosoras/Pigeon#10]
或者有没有办法增加如手机号，生日等字段，后台显示，前台模板可以调用

**Comment by kasuganosoras** [comment]
这个建议新增一个数据表单独储存数据

**Comment by xzyone** [comment]
不会开发。。。纯用户，作者大佬觉得这个功能有必要吗？以后会有机会添加吗

**Comment by kagurain** [comment]
纯粹的聊天感觉加这么多是没有必要的 有点会过于臃肿

**Comment by rywiki** [comment]
> 纯粹的聊天感觉加这么多是没有必要的 有点会过于臃肿

一次性加个文本描述字段，允许格式文本，如markdown就得了。谁想要什么内容，自己加就是了。这种信息放数据库，我觉得没什么必要

**Comment by kasuganosoras** [comment]
此功能可能不会实现，如果有需要可以进行二次开发
