### ISSUE TITLE
编辑内容时html标签字符转换问题

### ISSUE THREAD

**Issue by rywiki** [kasuganosoras/Pigeon#14]
在编辑已发布内容时，会将内容中带有的html标签字符（<，>，&等）进行替换，但data.content调用relpace时没有使用正则替换的全局标志g，故仅仅替换了首个字符，没有实现预定的功能。

ps：其实我不太理解这样做的意义。因为如果要发布html 的话，这样转换后1、不容易编辑，2、再发布就不是html了。这个是之前使用div而不是textarea所造成的吗？

**Comment by kasuganosoras** [comment]
这个问题呢，是因为最早开发的时候，服务端是没有对编辑内容进行预处理转义的，完全交给网页前端进行 js 处理转义，后来为了安全起见在服务端做了转义，结果经过客户端双重转义后就出现了这个问题。感谢修复。
