### ISSUE TITLE
会弹出（错误：undefined）提示

### ISSUE THREAD

**Issue by youranreus** [kasuganosoras/Pigeon#17]
装完之后，每隔一段时间会弹出个弹框
![image](https://user-images.githubusercontent.com/24204866/75085990-14147200-556a-11ea-8ec9-8213c17bb914.png)
看了一下控制台
![image](https://user-images.githubusercontent.com/24204866/75086001-3908e500-556a-11ea-85b9-23794642d84d.png)
大概是这个情况。dalao有时间的话帮忙看一下叭QAQ
https://bb.季悠然.space

**Comment by youranreus** [comment]
对不起，找到问题了，打扰了！

**Comment by givenhyh** [comment]
![图片](https://user-images.githubusercontent.com/37971883/75213455-23432c00-57c5-11ea-8a1a-9f5a4d4be52e.png)
那这个错误您解决没。。。难道只能屏蔽错误提示？
![同款错误](https://user-images.githubusercontent.com/37971883/75213493-3e15a080-57c5-11ea-9b30-7ea5aec70d29.png)

**Comment by givenhyh** [comment]
骚操作导致错误复现= =
其实就是把这个网页晾在浏览器里2个多小时
![图片](https://user-images.githubusercontent.com/37971883/75214186-a6658180-57c7-11ea-8492-874f5f51419a.png)
系统环境：Mac os X 10.11.5 Firefox 73.0.1(64x)

**Comment by givenhyh** [comment]
不止弹一个，弹了10多个
![图片](https://user-images.githubusercontent.com/37971883/75214297-02c8a100-57c8-11ea-8c10-22d0b7b20b44.png)

**Comment by youranreus** [comment]
丢，我这边没问题还以为解决了

**Comment by givenhyh** [comment]
可能是你没挂够时间吧hhh

**Comment by kasuganosoras** [comment]
这个问题只是因为网页端 Ajax 请求服务器失败了，然后就会蹦个 undefined 出来
解决方法的话，编辑模板的 footer.php，搜索 `alert("错误：" + htmlobj.responseText);`，大约在 115 行左右，把这里注释掉就行了

**Comment by youranreus** [comment]
get!舒服了

**Comment by yesmiley** [comment]
> ![图片](https://user-images.githubusercontent.com/37971883/75213455-23432c00-57c5-11ea-8a1a-9f5a4d4be52e.png)
> 那这个错误您解决没。。。难道只能屏蔽错误提示？
> ![同款错误](https://user-images.githubusercontent.com/37971883/75213493-3e15a080-57c5-11ea-9b30-7ea5aec70d29.png)

这个那你解决了吗，我也出现 underfined在注册页面

**Comment by givenhyh** [comment]
解决了，在8，11开头加一个@就好

**Comment by yesmiley** [comment]
@givenhyh 尴尬，我加了还是报错。你是不是还调整了其它地方

**Comment by youranreus** [comment]
我是这样解决的
```php
if(isset($_POST['username'])){
	if(preg_match("/^[A-Za-z0-9\_\-]+$/", $_POST['username'])) {
		$temp_user = isset($_POST['username']) ? $_POST['username'] : "";
	}
}
if(isset($_POST['email'])){
	if(preg_match("/^[a-zA-Z0-9]+([-_.][a-zA-Z0-9]+)*@([a-zA-Z0-9]+[-.])+([a-z]{2,5})$/ims", $_POST['email'])) {
		$temp_email = isset($_POST['email']) ? $_POST['email'] : "";
	}	
}
```

> @givenhyh 尴尬，我加了还是报错。你是不是还调整了其它地方

**Comment by givenhyh** [comment]
![图片](https://user-images.githubusercontent.com/37971883/76191179-bc3c6300-6219-11ea-8e6f-2b1e68d76886.png)
<?php
global $pigeon, $error, $alert;
if(!$pigeon) {
	exit();
}
$temp_user = "";
$temp_email = "";
if(preg_match("/^[A-Za-z0-9\_\-]+$/", @$_POST['username'])) {
	$temp_user = @isset($_POST['username']) ? @$_POST['username'] : "";
}
if(preg_match("/^[a-zA-Z0-9]+([-_.][a-zA-Z0-9]+)*@([a-zA-Z0-9]+[-.])+([a-z]{2,5})$/ims", @$_POST['email'])) {
	$temp_email = @isset($_POST['email']) ? @$_POST['email'] : "";
}
?>
			这是我的register.php上面的php内容

**Comment by givenhyh** [comment]
```
<?php
global $pigeon, $error, $alert;
if(!$pigeon) {
	exit();
}
$temp_user = "";
$temp_email = "";
if(preg_match("/^[A-Za-z0-9\_\-]+$/", @$_POST['username'])) {
	$temp_user = @isset($_POST['username']) ? @$_POST['username'] : "";
}
if(preg_match("/^[a-zA-Z0-9]+([-_.][a-zA-Z0-9]+)*@([a-zA-Z0-9]+[-.])+([a-z]{2,5})$/ims", @$_POST['email'])) {
	$temp_email = @isset($_POST['email']) ? @$_POST['email'] : "";
}
?>
			
```

**Comment by yesmiley** [comment]
> ```
> if(isset($_POST['username'])){
> 	if(preg_match("/^[A-Za-z0-9\_\-]+$/", $_POST['username'])) {
> 		$temp_user = isset($_POST['username']) ? $_POST['username'] : "";
> 	}
> }
> if(isset($_POST['email'])){
> 	if(preg_match("/^[a-zA-Z0-9]+([-_.][a-zA-Z0-9]+)*@([a-zA-Z0-9]+[-.])+([a-z]{2,5})$/ims", $_POST['email'])) {
> 		$temp_email = isset($_POST['email']) ? $_POST['email'] : "";
> 	}	
> }
> ```

捕捉季悠然大佬！
方法可行，多谢 O(∩_∩)O

**Comment by yesmiley** [comment]
> ```
> <?php
> global $pigeon, $error, $alert;
> if(!$pigeon) {
> 	exit();
> }
> $temp_user = "";
> $temp_email = "";
> if(preg_match("/^[A-Za-z0-9\_\-]+$/", @$_POST['username'])) {
> 	$temp_user = @isset($_POST['username']) ? @$_POST['username'] : "";
> }
> if(preg_match("/^[a-zA-Z0-9]+([-_.][a-zA-Z0-9]+)*@([a-zA-Z0-9]+[-.])+([a-z]{2,5})$/ims", @$_POST['email'])) {
> 	$temp_email = @isset($_POST['email']) ? @$_POST['email'] : "";
> }
> ?>
> 			
> ```

明白啦，谢谢哈，刚才at符号加错位置了
