### ISSUE TITLE
为什么图片是经过了站点代理的呢

### ISSUE THREAD

**Issue by yesmiley** [kasuganosoras/Pigeon#18]
通过图床外链插入的图片链接，变成了 https://站点/imgproxy
感觉无形之中浪费了图床的高速CDN，同时加重了站点本身的流量和网速负担

**Comment by rywiki** [comment]
我也发现了这个问题，代理我给去了。不过隐约觉得可能是安全性问题吧。

**Comment by yesmiley** [comment]
> 我也发现了这个问题，代理我给去了。不过隐约觉得可能是安全性问题吧。

可以问下你是怎么去除的么

**Comment by xzyone** [comment]
> 我也发现了这个问题，代理我给去了。不过隐约觉得可能是安全性问题吧。

您好，能讲一下怎样去除吗？

**Comment by xzyone** [comment]
> > 我也发现了这个问题，代理我给去了。不过隐约觉得可能是安全性问题吧。
> 
> 可以问下你是怎么去除的么

打开 parsedown.php 文件
在 protected function inlineImage($Excerpt) 内，的 'src' 一行改成：

`'src' => $Link['element']['attributes']['href'],`

**Comment by yesmiley** [comment]
> 您好，能讲一下怎样去除吗？

我已经去除成功了

在`/pigeon/parsedown.php`中

136行改成`'src' => $Link['element']['attributes']['href'],`即可

**Comment by xzyone** [comment]
> > 您好，能讲一下怎样去除吗？
> 
> 我已经去除成功了
> 
> 在`/pigeon/parsedown.php`中
> 
> 136行改成`'src' => $Link['element']['attributes']['href'],`即可

哈哈我也发现了
