### ISSUE TITLE
访问时报 http error 500

### ISSUE THREAD

**Issue by YHCClin** [kasuganosoras/Pigeon#19]
服务器环境php 7.2.27，安装成功后浏览器访问index.php 报500错误；loader.php 和 config.php 报过语法错误，我修改了下，然后在服务器上运行没有错误，但是客户端浏览器上访问依然500；我怀疑我的nginx配置出问题了便在同一目录下写了个简单的php文件进行浏览器访问，结果正常显示。所以应该是啥问题啊？？？，小白求教。谢谢。

**Comment by duoduoffff** [comment]
改配置文件，你是不是没开邮箱验证？如果没开，把邮箱那个位置写成 `False`，下面的 port 随便写个数字，比如 0 就好了

![image](https://user-images.githubusercontent.com/46983115/79638086-492df100-81b6-11ea-9852-d9d1ff2267ee.png)

**Comment by kasuganosoras** [comment]
我假设这个问题已经解决，如果有其他问题，请重新打开 Issues
