### ISSUE TITLE
注册页面出现以下字符

### ISSUE THREAD

**Issue by wyh2019666** [kasuganosoras/Pigeon#20]
Notice: Undefined index: username in /www/wwwroot/comments.mzrme.com/Pigeon/pigeon/template/pigeon/register.php on line 8

Notice: Undefined index: email in /www/wwwroot/comments.mzrme.com/Pigeon/pigeon/template/pigeon/register.php on line 11

**Comment by imxiaohu** [comment]
我也是

**Comment by q409640976** [comment]
虽然报错,但是不影响使用,无伤大雅

**Comment by rywiki** [comment]
需要在nginx和php，还有ci里面把报错信息都关了，就省心了。大多数错误好像都是ci的报错信息没有处理的缘故，问题不是很大，除非你发现页面出不来或者严重错误，否则这些信息可以忽略。

**Comment by ywyt** [comment]
修改template\你选择的主题\register.php
8-13行
```php
if(array_key_exists('username', $_POST) && preg_match("/^[A-Za-z0-9\_\-]+$/", $_POST['username'])) {
	$temp_user = isset($_POST['username']) ? $_POST['username'] : "";
}
if(array_key_exists('email', $_POST) && preg_match("/^[a-zA-Z0-9]+([-_.][a-zA-Z0-9]+)*@([a-zA-Z0-9]+[-.])+([a-z]{2,5})$/ims", $_POST['email'])) {
	$temp_email = isset($_POST['email']) ? $_POST['email'] : "";
}
```

**Comment by kasuganosoras** [comment]
我假设这个问题已经解决，如果有其他问题，请重新打开 Issues
