### ISSUE TITLE
疑似一个小bug

### ISSUE THREAD

**Issue by CMCboy** [kasuganosoras/Pigeon#22]
我在在安装时就配置smtp信息会导致config.php文件的中文出现乱码，在安装时不配置smtp信息就不会出现这样的情况。【黑人问号脸】

**Comment by rywiki** [comment]
> 我在在安装时就配置smtp信息会导致config.php文件的中文出现乱码，在安装时不配置smtp信息就不会出现这样的情况。【黑人问号脸】

web安装吗？

**Comment by kasuganosoras** [comment]
请使用 UTF-8 编码运行安装程序
```
chcp 65001
```
如有其它问题，请重新打开 Issue
