### ISSUE TITLE
【疑似BUG】使用recaptcha后登录极其缓慢及其他问题

### ISSUE THREAD

**Issue by Beattheend** [kasuganosoras/Pigeon#24]
### 问题1
正确配置recaptcha后前端加载recaptcha后验证成功点击登录一直处于加载中，然后502收场！最后不得已关闭recaptcha验证！这是bug？还是？
reCAPTCHA 类型：v2 复选框 已正确配置
### 问题2
登录后台后有几率出现“Unexpected end of JSON input”报错，（刷新页面）！

**Comment by kasuganosoras** [comment]
因为 Google 被墙了所以无法完成 reCAPTCHA 验证
解决方法修改 `pigeon/function.php` 文件第 55 行左右的网址，改为
```php
$result = file_get_contents('https://recaptcha.net/recaptcha/api/siteverify', false, $context);
```
就可以走 reCAPTCHA 的国内镜像服务器
