### ISSUE TITLE
希望添加图片上传及显示功能

### ISSUE THREAD

**Issue by ppbibo** [kasuganosoras/Pigeon#26]
看到了该功能点支持markdown，希望博主加个上传文件的功能。
![image](https://user-images.githubusercontent.com/36287351/95213154-14bff700-0821-11eb-8695-cb974618ea8e.png)

**Comment by rywiki** [comment]
之前是提了一个上传到图床的pr，不知道和并没有。一定要放在自己的服务器上吗？

**Comment by ppbibo** [comment]
> 之前是提了一个上传到图床的pr，不知道和并没有。一定要放在自己的服务器上吗？

不一定放到自己服务器，图床也一样的，因为很多人不懂markdown语法导致不知道可以传照片，最好可以直接把图片复制黏贴到上面，增加一个上传图片的表单啥的。

**Comment by rywiki** [comment]
> > 之前是提了一个上传到图床的pr，不知道和并没有。一定要放在自己的服务器上吗？
> 
> 不一定放到自己服务器，图床也一样的，因为很多人不懂markdown语法导致不知道可以传照片，最好可以直接把图片复制黏贴到上面，增加一个上传图片的表单啥的。

如果是这样，你可以去看看我修改的模版。应该就是两行代码的事情。这个需求可能还是自己定制比较好，作者可能时间有限吧，如果上传到本地，肯定还是得规划规划。只是插入图床的照片，简单一点
https://github.com/rywiki/Pigeon/tree/master/pigeon/template/pigeon

![image](https://user-images.githubusercontent.com/7971101/95702493-0fc6d180-0c7f-11eb-864e-66e073499902.png)

**Comment by ppbibo** [comment]
> > > 之前是提了一个上传到图床的pr，不知道和并没有。一定要放在自己的服务器上吗？
> > 
> > 
> > 不一定放到自己服务器，图床也一样的，因为很多人不懂markdown语法导致不知道可以传照片，最好可以直接把图片复制黏贴到上面，增加一个上传图片的表单啥的。
> 
> 如果是这样，你可以去看看我修改的模版。应该就是两行代码的事情。这个需求可能还是自己定制比较好，作者可能时间有限吧，如果上传到本地，肯定还是得规划规划。只是插入图床的照片，简单一点
> https://github.com/rywiki/Pigeon/tree/master/pigeon/template/pigeon
> 
> ![image](https://user-images.githubusercontent.com/7971101/95702493-0fc6d180-0c7f-11eb-864e-66e073499902.png)

感谢回复，这个试了一下还可以，但是出现了一些问题，我的国内服务器在显示的时候提示502页面，
![image](https://user-images.githubusercontent.com/36287351/95708321-86b79680-0c8e-11eb-9382-18326a9c276e.png)

最好的话还是本地或者阿里云/腾讯云/主流/oss云上，本地的话想到了 base64的方式存储。

markdown 
![image](https://user-images.githubusercontent.com/36287351/95708387-ac44a000-0c8e-11eb-816b-de3068173b40.png)

参考：https://www.jianshu.com/p/280c6a6f2594

**Comment by rywiki** [comment]
这个问题可能是直接使用作者的图片代理导致的吧。imgchr的图片返回的肯定不是直接返回图片，而是至少做了个跳转或者其他什么的。抛开那个代理可能会简单一点。你说的这个其实直接实现挺简单，完全可以在客户端调用window.btoa()完成，只不过，图片转base64挺大的，如果不在编辑框上做处理（比如内容隐藏或者折叠）那编辑起来会很难受。而且，上传文件还有安全性问题。

**Comment by ppbibo** [comment]
base64 确实挺大的对用户也不太友好，上传文件安全性问题最简单且有效的解决方法就是图片后缀白名单，静态资源目录禁止文件执行权限，当然这是上传到服务器本地的情况下。

**Comment by kasuganosoras** [comment]
已在最新版本中合并
