### ISSUE TITLE
CSRF问题

### ISSUE THREAD

**Issue by Tnze** [kasuganosoras/Pigeon#3]

**Comment by Tnze** [comment]
应该把登出、删除post等请求改为用POST而不是GET，这样当管理员在其他网站看到[奇怪的链接](https://pigeon.ssr.wine/?s=deletepost&id=117)然后又很好奇……

**Comment by kasuganosoras** [comment]
用户登陆后生成一个随机 session id，在执行操作时附带上 session id 即可
这样不需要进行太大的改造（懒

**Comment by kasuganosoras** [comment]
问题已修复，目前已经针对所有操作进行了 CSRF 防护
