### ISSUE TITLE
请问作者最近的release用的哪一个版本的php？是不是我太菜了代码在我电脑还出了好几个bug？作者用的php版本是？

### ISSUE THREAD

**Issue by 25thengineer** [kasuganosoras/Pigeon#30]
接题目：
另外，我在安装时已经设定不用邮箱验证了，但在网页注册时，却仍然提示**“系统已发送一封邮件到您的邮箱，请点击邮件中的链接完成验证。”**
这是什么bug吗？
smtp.php有几处冒红……
希望作者大佬给出开发工具的具体版本啊~~~

**Comment by kasuganosoras** [comment]
我用的是 PHP 7.4，系统是 Linux
有错误的话检查下 PHP 的 error reporting 是不是设置的太严格了

**Comment by kasuganosoras** [comment]
我假设这个问题已经解决，如果有其他问题，请重新打开 Issues
