### ISSUE TITLE
使Pigeon不联网也可以使用 - [网络资源本地化]

### ISSUE THREAD

**Issue by jasondayee** [kasuganosoras/Pigeon#33]
![image](https://user-images.githubusercontent.com/9551120/104148792-9ae66d80-540e-11eb-8177-2caa34320651.png)

**Comment by jasondayee** [comment]
头像问题确实需要单独处理，
我在本地为了可以不连外网使用暂时将头像资源下载成静态
可以单独做一个issue 支持用户上传头像并给一些默认头像

**Comment by kasuganosoras** [comment]
现阶段没有需求也没有必要将资源本地化，因为 Pigeon 最初的设定就是一个互联网公开留言板，而不是设计在没有外网的环境下使用的。并且像 Bootstrap、jQuery 这些都是互联网上随处都可以获得的资源，使用大厂的 CDN 速度和稳定性相对来说都会比自建的更快更好。真的有需要在内网使用的人根据情况自己修改一下代码就可以了，不需要合并到主分支里面。
