### ISSUE TITLE
Pigeon MySQL 默认编码格式问题

### ISSUE THREAD

**Issue by jasondayee** [kasuganosoras/Pigeon#35]
由于项目没有设置编码格式,导致项目使用PHP默认的 `Latin1` 格式操作数据库,
迁移数据时会显示中文乱码

<img width="470" alt="image" src="https://user-images.githubusercontent.com/9551120/104158191-cf1a5800-5427-11eb-8fe9-997b28d33c78.png">

但是发现初始化创建的表结构使用的是 `utf8mb4_unicode_ci`
大概猜测作者本意应该是想使用 `UTF-8` 格式操作数据库

可以在 ` 	构造函数，初始化 MySQL 连接 `后加上一句 ` mysqli_query($this->conn,"SET NAMES UTF8"); ` 
设置默认编码格式为 `UTF-8` 来解决编码格式问题

但考虑历史数据问题,需要写一个PHP脚本转换 `Latin1`  -> `UTF8 ` 
否则历史数据会显示乱码 

待完成 ...

**Comment by kasuganosoras** [comment]
使用 utf8mb4 是因为 utf8 无法支持 Emoji，如果发表的内容中存在 Emoji 表情，然后使用了普通的 utf8 编码作为储存格式的话，会导致存入数据库后出现乱码，使用 utf8mb4 就不会出现这个问题。

**Comment by jasondayee** [comment]
在我本地我把数据库编码格式和table编码格式都改成了 `utf8` 
PHP 连接MySQL设置编码格式 `Latin1` 或者不手动设置 都是可以正常发布和显示 Emoji 表情的 

**但是为了支持 Emoji 确实不需要修改编码格式为UTF-8**

此Issue 可以关闭 ...
