### ISSUE TITLE
安装时出错

### ISSUE THREAD

**Issue by Hallon233** [kasuganosoras/Pigeon#4]
> 请输入管理员账号 (Admin)> HallonZhu  
请输入管理员密码 (2759bb60e186eb2b)> ***********  
请输入管理员邮箱 (admin@example.com)> **********  
PHP Fatal error:  Call to undefined function password_hash() in /root/Pigeon/install.php on line 143  
Fatal error: Call to undefined function password_hash() in /root/Pigeon/install.php on line 143  

问题如上,谢谢

**Comment by kasuganosoras** [comment]
请用 PHP 5.6+，推荐 PHP 7+

**Comment by Hallon233** [comment]
已解决,THX!
