### ISSUE TITLE
注册用户报错

### ISSUE THREAD

**Issue by AoiKaede** [kasuganosoras/Pigeon#46]
Warning: Use of undefined constant n - assumed 'n' (this will throw an Error in a future version of PHP) in /www/wwwroot/Pigeon/pigeon/config.php on line 15

Fatal error: Uncaught Error: Call to undefined function ereg_replace() in /www/wwwroot/Pigeon/pigeon/smtp.php:136 Stack trace: #0 /www/wwwroot/Pigeon/pigeon/smtp.php(119): smtp->smtp_sockopen_mx() #1 /www/wwwroot/Pigeon/pigeon/smtp.php(64): smtp->smtp_sockopen() #2 /www/wwwroot/Pigeon/pigeon/function.php(342): smtp->sendmail() #3 /www/wwwroot/Pigeon/pigeon/loader.php(181): Pigeon->sendMail() #4 /www/wwwroot/Pigeon/index.php(8): include('/www/wwwroot/Pi...') #5 {main} thrown in /www/wwwroot/Pigeon/pigeon/smtp.php on line 136

**Comment by kasuganosoras** [comment]
检查 `/www/wwwroot/Pigeon/pigeon/config.php` 中的邮件 SMTP 发信配置，应该是内容有误
