### ISSUE TITLE
检查更新的地址 SSL 证书已过期，无法获取最新版本信息

### ISSUE THREAD

**Issue by comdotwww** [kasuganosoras/Pigeon#48]
https://cdn.tcotp.cn:4443/pigeon/

![证书过期](https://user-images.githubusercontent.com/62149924/181890701-baf8ff1f-488f-4cd6-989d-2080d0d316aa.png)

**Comment by kasuganosoras** [comment]
可改用 https://cdn.zerodream.net/pigeon/

**Comment by kasuganosoras** [comment]
在最新的更新中已修复：https://github.com/kasuganosoras/Pigeon/commit/428ce2c7be8742c1a674252b2c3b73832c79d376
