### ISSUE TITLE
这个是不是数组报错

### ISSUE THREAD

**Issue by 11195666** [kasuganosoras/Pigeon#49]
Notice: Trying to access array offset on value of type bool in /www/wwwroot/mypage/pigeon/function.php on line 178

$html .= "<tr><td class='headimg'><img src='https://gravatar.loli.net/avatar/" . md5($this->getUserInfo($rw[2])['email']) . "?s=64'</td><td class='thread'><p><small>{$rw[2]} 发表于" . $this->getDateFormat($rw[3]) . "&nbsp;&nbsp;<a href='?s=msg&id={$rw[0]}' target='_blank'><i class='fa fa-external-link'></i></a>" . $pstatus . str_replace("{id}", $rw[0], $sdelete) . "</small></p>";
$html .= "<div class='message'>" . $Markdown->text($rw[1]) . "</div></td></tr>";

**Comment by 11195666** [comment]
php7.4报错，切换为7.2正常

**Comment by 11195666** [comment]
Notice: Undefined index: username in /www/wwwroot/mypage/pigeon/template/pigeon/register.php on line 8

Notice: Undefined index: email in /www/wwwroot/mypage/pigeon/template/pigeon/register.php on line 11

注册界面显示以上报错

**Comment by kasuganosoras** [comment]
这个只是提示，不影响程序实际运行
可以通过修改 php.ini 屏蔽掉提示
```ini
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
```
