### ISSUE TITLE
后台管理怎么跳转不了

### ISSUE THREAD

**Issue by zzujay** [kasuganosoras/Pigeon#5]
访问admin.php时为什么总跳转wampsever页面

**Comment by kasuganosoras** [comment]
检查你的 rewrite 设置，还有 Nginx 设置，如果方便的话提供一下截图

**Comment by Mr96s** [comment]
> 访问admin.php时为什么总迁移wampsever页面

只有admin和root权限用户才可以访问，你管理员身份登陆后就可以了。

**Comment by kasuganosoras** [comment]
我假设这个问题已经解决，如果有其他问题，请重新打开 Issues
