### ISSUE TITLE
关于 install.php 中启用注册邮箱验证功能的一处错误

### ISSUE THREAD

**Issue by zurica2013** [kasuganosoras/Pigeon#57]
应该是手滑了 :smile:
[ Line 91 中的 $smtp_host ](https://github.com/kasuganosoras/Pigeon/blob/bcf02b87262d450e475e5a424ba76aac51f7c1a0/install.php#L91)应为 $input ，不然怎么填写 SMTP 服务器地址都是错误

**Comment by kasuganosoras** [comment]
嗯，Github Copilot 补全偶尔也是会补出问题的，已经修复了
