### ISSUE TITLE
安装方式简便一下

### ISSUE THREAD

**Issue by wxcgeek** [kasuganosoras/Pigeon#8]
我是本地搭建好，再上传到虚拟空间的。虚拟php空间不支持命令行操作。
大佬能不能改成直接访问网页安装，方便一下小白。

**Comment by kasuganosoras** [comment]
请参考 wiki：[手动安装 Pigeon](https://github.com/kasuganosoras/Pigeon/wiki/Install#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85-pigeon)

**Comment by yesmiley** [comment]
@kasuganosoras 演示站打不开了，那个文件可以发在github吗

**Comment by wb0808** [comment]
有网页安装就好了 https://pigeon.ssr.wine/install-sql.html 这个打不开了

**Comment by kasuganosoras** [comment]
https://tql.ink/install-sql.html

**Comment by kasuganosoras** [comment]
我假设这个问题已经解决，如果有其他问题，请重新打开 Issues
